name: proj4dart
description: Proj4dart is a Dart library to transform point coordinates from one coordinate system to another, including datum transformations (Dart version of proj4js/proj4js).
version: 1.0.5
homepage: https://github.com/maRci002/proj4dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mgrs_dart:
    git:
      url: https://github.com/p-shapovalov/mgrs_dart.git  
      ref: 39bab418595ae3fd4fb2c65099fb97bfbdf805a2
  wkt_parser: 
    git:
      url: https://github.com/p-shapovalov/wkt-parser-dart.git  
      ref: a411504847c3b19353ddfd5c440e9d3c28838cab
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.1
